### ISSUE TITLE
StreamMaster constructor does not return if Kafka broker unreachable

### ISSUE THREAD

**Issue by dominikwerder** [ess-dmsc/kafka-to-nexus#26]
The constructor of class `StreamMaster` does not return if the Kafka broker is unavailable.

If the class `Master` creates a `StreamMaster` without available broker, then control is not returned to the `Master` class, the program hangs and `Master` can not even detect that because its thread got 'stolen' :smiley:

**Comment by michele-brambilla** [comment]
Fixed in branch _status_. The actual issue was in the ``Streamer`` constructor. Now the constructor fires a thread that performs the connection, forget about it and return immediately. So the ``StreamMaster`` constructo does. A mutex in the ``Streamer`` makes sue that the connection is complete before trying to write or search the timepoint. If the connection fails an error flag is raised.
