### ISSUE TITLE
Argument parser in unit test application crashes 

### ISSUE THREAD

**Issue by SkyToGround** [ess-dmsc/kafka-to-nexus#38]
The `kafka-to-nexus/src/tests/tests.cxx` file (used to run unit tests) implements an argument parser on top of (and before) the GoogleTest argument parser. Thus when trying to pass arguments to GoogleTest, the application crashes (exits).

There are a few alternatives to fixing this problem:
1. Allow the other parser to pass arguments through to GoogleTest.
2. Some of the tests run by that application are not actually unit tests but integration tests. Thus an alternative is to split the application into two, one that runs unit tests and one that runs integration tests.

**Comment by matthew-d-jones** [comment]
This causes a problem for me too, because my IDE expects to be able to pass a couple of arguments to googletest to generate the output it uses to display test information in the GUI.
It is possible to pass arguments to your tests through googletest anyway, so the additional parser should not be required.
Regardless, I think separating integration tests or otherwise making it clear which are integration tests is a good idea.

**Comment by matthew-d-jones** [comment]
This issue was closed by #44
